gitlabUrl: https://git.urosevicvuk.dev

# Runner registration token â€” create a secret named gitlab-runner-secret
# with key runner-registration-token or runner-token
runners:
  secret: gitlab-runner-secret
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "system-cicd"
        image = "alpine:3.21"
        privileged = false
        cpu_request = "100m"
        memory_request = "128Mi"
        cpu_limit = "500m"
        memory_limit = "512Mi"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
