---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: system-monitoring
spec:
  encryptedData:
    admin-password: AgCHwRaPUy+dMOHBm4jaMAd+yZJZSlkPOvh/ZiyRZBMeaBmudJ3ZF2cXR1LaYFBdxb7o4eViljiw47p1c+4TrTk4q514jqszABd1iLLZbAOvkO4ueSJvGsYfoJEJonQU1fARcetpztvJx9pIPAvBN9I7ckFGMZ8NgyA3dx1MyJNoFQJ/WhvSCAADT4CTBfB4HtfCO6Q60xv1RlwFMpnqeBDP9cp9dF00Wauj/Xl41izD2b6w2/tdZ1RkaIRDLdtLJCJd3Jyj+u3EBu0A/25oZkhZHE3msdmFJHMcRbcsO4CZAjJ3LL63ivWF2x/eW0nRt0JyeRGP83XKAycorYhQoagz0FIFx4wtWrtX2J3Hp0+tbIuyh++Fqy/UVe9WHpV9EwHJXDBCpYRuKYTnnP2jSi6OgvFZMZIUwlgk4/mm45uh1h7EncH+40QMUUBFsRzCW6WvPXkOKNX+WAlrXEO5X9SoqRCcFnq5B6hWJV/leiyTGkJZIDx8TcnNWHOqMc2nMe2wzgOxXgFVP3+w/gXAf6K4V7y7b8gPStcl7RVGSgQpr0HIMrcq6pBqhz7oyPnQU9BdFAzQff3/wDAdfhN4kNcsWoS/ZhOyLIzmOZ82AU8+Hg1/FfBnhxhO/aGvt2QvBys0TQjhFOZxwQ+wCt5UBiRVO4dJWf2P3UyYjVrCQ7odgkRd+jDGTn0d5m3vRxs3Y0+v0T10F+XMD80JvrM=
    admin-user: AgA9wkUtz3ComWbn59sGYmulv2twysgzG7mKs5kppSVSuhrSLh7uGMoBPILE8SfbPRQ4EgYVi0ksYnYVqcWn7v9jIdFLUJ2vZzm23KNW0j7B20vMy+cJjJE5FR+4uXDBgWWxXxv/MDA8mCl3DdojuUrv7ucSAV+6ZQO4bvhf9B80/C9HN1fOrX1716UUVk331ejeSF3swu84yB7sPd37YUj9rLA8w8ZghbKzgHHLKBn8tdAktEiz0AzeBjrRfxw8RS4dzXkAbYo557WHKruT0IwYdcnBv4xI2fzYcJGupX7TAfDoanuc3Vcpn/dIKIGQ0xi09wcB60pADiPPCGeX0uYn33Nxw1OKYTQXpLyDQT6BFEM/LNINX/VXp8s7UFMov0bWvwYAhdYQPtbFWR19c9/BvL6gRWV98sxuFOAbT6VyDp56CCZoaLjyclEkye0xv4JiDOi8XdXI6Ml6uHEjsXt2beeg/dpMM92TGS7N+ri6EqV9Xo4pF8JYRjc8hgu7Tzn1ym29J6K2ZxlzxVpk5oxcKxvW8DoEQVY8FYsL7lMgaZhbl4Lx8mH2MtMO69qLLypoupr5tH7douJRqwTo58KV7mDqzD9fpEGyjyPgsrutoYKw8xkYdQonPBLQU45uMDI1hO9jvaGLZ2cfpBIMlREgtrZI4YvGvMSVyh5fVFckPZwDouXFMJg+X+809xoAUqr4QHOl
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: system-monitoring
    type: Opaque
