---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCbkR/jqwXKOivM5gEbeSh14wJy4KVKe9rOiRAhuv53jCSJla8O8FAo7w37EkE7HckQpEBmmdcCraBaRO56qMUBLLz1jIoQrxQ6T0B/w3O+NkiRjMz3KshFJqNplqtgZ1wkvU3/UPlGRbsZn79rCMo1JVVTsbP913MeMpNGSktITMKjvVMxU3X3xDgaeO8qO3xuQB4Ss/brOpYBNS5gcRpiX1baPVNmo2CagTVw6uyhewsp9x5zA1owXE0woGxiK2jeVaoneTCoAOWFRVwmhk+vmOVPE8O9Orb+B9Jg+I0H7uQCAZwbUZpMjtiyDN57getE69qg7hMjFNQHo/asiKL1tvPmo+K7nV6/DExzMA3N9QwMtjfbn8OLF41qWyqbELmsLhJ1gEnLGJ8NByvsK5UrGcIsnYrC3vcXtuyvDfnIztE+P4AdjflE2YjxNgDH39fRfmo0WOjyXyraCFj/O/DXT/PZ/BCMBhjN1wkrQ3v3dAnXPYj3mblp1x1hVdTSNoo7NhvZhQCoYgx/MMs1Io1WsZpw+cKtYC6IWzmb4W4hOFQHwM5Dovd2en7v71OjlWAn2ipMQkRNcaXPwyh70nhSiAnrRZMtIjFvHij4/iadmIYKddkFU/XMvJl0SUohhba23HokAhDPA5BKwzFRrUam4TpmogFjGF7XpLlHQ3KRw+hrr045zLZ00v9pOYTHSLQVmRjmSLFtA1VVfQE=
    admin-user: AgBt+RXXHHE+UNno2s0GW9F1HEpBmOJbxyT2FlIpX6Ju38RcVTYCCT+xeqSdYsMn4grYLX8u41RONcD7+5p4NnpXRe7A9VdAG55wOHLekYYSRF/c/9KbsVCF9MgC+u8t+bq4e3laNbmUXkj4uBCfOTqCcmvvY2NVKxeeny2/xX+ToMnfcbcudXZzQDWAtHtPaOD7nymKWxuSnibrOaQPTlcmJjgWWC+6t37865vXSSmJlvLSsLk9tOJjSRRHQPLypNztIFogwill7PxkMATeaRGqu/Bvs1qVHDqnCU5A3OMlC+ttbryTRZ1NSsaFRzZmGI/sAncN+NBlMEVQJnO9dA24VrQiFAhyN39gJOZIW5dRHCSyZO/VcyZ7iyTtU2hZ6cCCg80bYErbpZuwAtLH8O0IFmjjSFIbwSbU3/tiVyDrmYj6zAwzo9ttFhLY/iDsYKWXqLWQQ3lgC5DWz/2EXagIKhgCLkQ0wGaKq54kyXIkcxoBbk4mnMnQlGpyD9kbymgeEw7iGu+KOf5kqj6R8sUAqlC8d9A/1rFG+k4QEv96BXaYhvKpbbQbPS1cT2smhkOCLEweJDjcXGHJltxqgytTXjVpORCUHoKnPJw1lkjdXH5Uj/+FQ/xToLHKZXd/vEAbu8K9fU1+zqMtEmHDH33T9KVJoWo2bO0jyocjdhrP1ZZC+utq5MuC0Icof4bHC3VKIgeG
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
